import type {Metadata} from "next";
import "./global.css";
import QueryProvider from "@/components/QueryProvider";
import {Providers} from "@/app/provider";


// import { Geist, Geist_Mono } from "next/font/google";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <QueryProvider>
            <Providers>
            {children}
           </Providers>
        </QueryProvider>
        </body>
        </html>
    )
}